source :rubygems
source "http://gems.github.com"

gem 'rake', '0.9.2'
#gem 'mysql', '2.8.1'
gem 'mysql2', '0.2.7'
gem 'rails', '3.0.10'
gem 'jquery-rails', '0.2.5'
gem 'configatron', '2.6.4'
gem 'devise', '1.2.rc'
gem 'omniauth', '0.1.6'
gem 'simple-navigation', '3.0.2'
gem 'formtastic', '1.2.0'
gem 'tabletastic', '0.2.1'
gem 'flutie', '1.1.2'
gem 'inherited_resources', '1.1.2'
gem 'will_paginate', '3.0.pre2'
#gem 'hoptoad_notifier'
#gem 'heroku'
#gem 'taps'
gem 'acts_as_commentable'
gem 'acts-as-taggable-on'
gem 'rails_admin', :git => 'git://github.com/sferik/rails_admin.git', :branch => 'rails-3.0'
gem 'sunspot_rails', '1.2.1'
#gem 'feedtools', :path => 'vendor/gems/feedtools'
gem 'simple-rss'
gem 'paperclip', '2.3.5'
gem "recaptcha", :require => "recaptcha/rails"

group :test, :development do
	gem 'railsmachine'
#  gem 'mongrel', '1.2.0.pre2'
#  gem 'sqlite3-ruby', '1.3.2'
#  #gem 'redgreen', '1.2.2'
#  gem 'rr', '1.0.2'
#  gem 'factory_girl_rails', '1.0'
#  gem 'rspec-rails', '2.2.1'
#  gem 'cucumber', '0.9.4'
#  gem 'cucumber-rails', '0.3.2'
#  gem 'shoulda', '2.11.3'
#  gem 'email_spec', '1.0.0'
#  gem 'launchy', '0.3.7'
#  gem 'capybara', '0.3.9'
#  gem 'capybara-mechanize', '0.2.3'
#  gem 'autotest-rails', '4.1.0'
#  gem 'autotest', '4.4.1'
#  gem 'vcr', '1.3.3'
#  gem 'webmock', '1.6.1', :require => false
#  gem 'rails_best_practices', '0.4.5'
#  gem 'rails3-generators', '0.14.0'
#  gem 'rcov', '0.9.9'
end
